// Wörtliche Kopie von gg-immohandel src/lib/begleitscheinVorlage.ts (aus der Excel F001 erzeugt).
// ══════════════════════════════════════════════════════════════
// GENERIERT — nicht von Hand bearbeiten.
// Quelle: F001_Ankauf_Begleitschein_13022025_GW 1.xlsx
// Neu erzeugen: node scripts/gen-begleitschein-vorlage.mjs <xlsx>
//
// 1:1-Übernahme der Ist-Excel nach §A6/§G der Anforderungsliste.
// Ebene 1: 11 · Ebene 2: 75 · Ebene 3: 47 · gesamt 133
// ══════════════════════════════════════════════════════════════

/** Rohzeile der Auslieferungsvorlage. Wird beim ersten Start in die Vorlage kopiert. */
export interface VorlageSeedRow {
  id: string;
  lvl: 1 | 2 | 3;
  text: string;
  verantwortung?: string;
  sub?: string[];
}

/** Kopfbereich der Excel (G2a) — bleibt Freitext, wird manuell gepflegt. */
export const ANKAUF_KOPF = 'Ankaufsprozess: (Objekt, VE und wichtige Infos hier)';

export const ANKAUF_SEED: readonly VorlageSeedRow[] = [
  { id: "r11", lvl: 1, text: "Kaufmännisch / Projekt" },
  { id: "r12", lvl: 2, text: "Projekt mit allen durchsprechen und Themen zum eruieren sammeln" },
  { id: "r13", lvl: 2, text: "Projektkosten finalisieren für Kundenangebot." },
  { id: "r14", lvl: 2, text: "Restnutzungsdauer kostenlose Einwertung" },
  { id: "r15", lvl: 3, text: "Kosten für folgende Maßnahmen einholen:" },
  { id: "r16", lvl: 3, text: "Förderfähigkeit für die Maßnahmen einholen:" },
  { id: "r17", lvl: 3, text: "GW Kalkulation für Kunden finalisieren." },
  { id: "r18", lvl: 3, text: "Projekt und Verkaufsordner (inkl. Datenraum) anlegen und Unterlagen entsprechend einsortieren (Vordruck F000 enthält den Verkaufsordner und F005 beinhaltet die notwendigen Unterlagen)" },
  { id: "r19", lvl: 2, text: "Kundenansprache - wer sind mögliche Kunden aus unserer Kartei? Über welche Vertriebskanäle planen wir zu gehen?" },
  { id: "r21", lvl: 1, text: "Steuerliche Due Diligence" },
  { id: "r22", lvl: 2, text: "Kaufpreisanteil Grund und Boden (nur wenn IVT verkauft)", sub: ["im Ankauf keine Aufteiling"] },
  { id: "r23", lvl: 1, text: "Rechtliche Due Diligence" },
  { id: "r24", lvl: 2, text: "Mietverträge und Nachträge prüfen" },
  { id: "r25", lvl: 2, text: "Auflistung aller weiterer Dokumente aus Datenraum / Datenpaket, die geprüft werden müssen:" },
  { id: "r26", lvl: 2, text: "Grundbuchauszug prüfen" },
  { id: "r27", lvl: 2, text: "Teilungserklärung und Teilungspläne prüfen" },
  { id: "r28", lvl: 2, text: "Bewilligungsurkunden für alle Grunddienstbarkeiten anfordern & prüfen" },
  { id: "r29", lvl: 2, text: "Kaufvertrag" },
  { id: "r30", lvl: 3, text: "Kaufvertragsentwurf vorhanden?" },
  { id: "r31", lvl: 3, text: "Kaufvertragsentwurf intern prüfen", sub: ["langes Zahlungsziel mind. 3 Monate (Zahlbar ab Fälligkeit aber spätestens in 3 Monaten)","Vollmacht gegenüber Baurechtsamt auf eigene Kosten und Risiko Bauanträge zu stellen?"] },
  { id: "r32", lvl: 3, text: "Kaufvertrag final freigegeben" },
  { id: "r33", lvl: 2, text: "Datenraum vollständig plausibilisieren und hier zu klärende Fragen notieren" },
  { id: "r34", lvl: 2, text: "Verwaltervollmacht (Vordruck: Paperless -> Templates \"Verwaltungsvollmacht) bei Ankauf IVT, Verwaltervertrag bei Verkauf von IVT (Vordruck: Paperless -> Templates \"Verwaltervertrag\") abschließen" },
  { id: "r35", lvl: 2, text: "Projektkonto eröffnet? - muss spätestens nach Notartermin eröffnet werden", sub: ["9000er macht Sven","5000er macht Susanne"] },
  { id: "r36", lvl: 2, text: "Notartermin Datum:" },
  { id: "r37", lvl: 2, text: "Track Record Tabelle aktualisiert" },
  { id: "r38", lvl: 1, text: "Technische Due Diligence" },
  { id: "r39", lvl: 2, text: "Wird eine technische DD benötigt?" },
  { id: "r40", lvl: 2, text: "Baugenehmigungen" },
  { id: "r41", lvl: 3, text: "Ist der letzte genehmigte Stand mit der aktuellen Nutzung übereinstimmend?" },
  { id: "r42", lvl: 3, text: "Sind alle Baugenehmigungen mit Stempel vorhanden?" },
  { id: "r43", lvl: 3, text: "Sind alle Grundrisse mit Stempel vorhanden?" },
  { id: "r44", lvl: 2, text: "Gibt es eine gestempelte Flächenberechnung eines Architekten?" },
  { id: "r45", lvl: 2, text: "Flächen plausibilisieren mit eigenem Aufmaß der Grundrisse und/oder Referenzmaßen vor Ort" },
  { id: "r46", lvl: 2, text: "Baulasten prüfen" },
  { id: "r47", lvl: 2, text: "Negativzeugnis Denkmalschutz" },
  { id: "r48", lvl: 2, text: "Altlasten prüfen" },
  { id: "r49", lvl: 2, text: "Gebäudeversicherungsnachweis" },
  { id: "r50", lvl: 2, text: "Energieausweis vorhanden?" },
  { id: "r51", lvl: 1, text: "Finanzierung und KP-Zahlung" },
  { id: "r52", lvl: 2, text: "Liquiditätsplanung und Projektkosten festlegen" },
  { id: "r53", lvl: 3, text: "welche Kosten sind für das Projekt budgetiert und freigegeben" },
  { id: "r54", lvl: 3, text: "EK-Anteil an Bank kommuniziert:", sub: ["EK-Anteil zusätzlich eingeplant:"] },
  { id: "r55", lvl: 3, text: "FK Anteil:" },
  { id: "r56", lvl: 2, text: "Finanzierungspräsentation erstellen" },
  { id: "r57", lvl: 3, text: "Inhalte Finanzierungspräsentation füllen" },
  { id: "r58", lvl: 3, text: "Kalkulation für Bank" },
  { id: "r59", lvl: 3, text: "Energieausweis" },
  { id: "r60", lvl: 3, text: "Baugenehmigung als 1 PDF" },
  { id: "r61", lvl: 3, text: "Flächenberechnung als 1 PDF" },
  { id: "r62", lvl: 3, text: "Gestempelte Grundrisse als 1 PDF" },
  { id: "r63", lvl: 3, text: "Gebäudeversicherungsnachweis" },
  { id: "r64", lvl: 2, text: "Welche Gesellschaft kauft?" },
  { id: "r65", lvl: 2, text: "Kreditanfrage stellen" },
  { id: "r66", lvl: 3, text: "Grundschuld enge Zweckerklärung" },
  { id: "r67", lvl: 3, text: "Grundschuld Anteil vollstreckbar und nicht vollstreckbar" },
  { id: "r68", lvl: 3, text: "Quotale Rückführung vereinbaren" },
  { id: "r69", lvl: 3, text: "Bank mitteilen, dass in der Zukunft saniert wird für Aufbau/Sanierungsfinanzierung" },
  { id: "r70", lvl: 3, text: "Kreditvertrag abgeschlossen" },
  { id: "r71", lvl: 3, text: "Grundschuldbestellungsunterlagen vor dem Notartermin erhalten" },
  { id: "r72", lvl: 3, text: "Bank informieren über welches Konto Darlehensrate eingezogen wird" },
  { id: "r73", lvl: 1, text: "Nach Notartermin: IVT Systemintegration" },
  { id: "r74", lvl: 2, text: "Notartermin Nachbesprechen" },
  { id: "r75", lvl: 2, text: "KV-Abschrift in DATEV (Alisa)" },
  { id: "r76", lvl: 2, text: "Finanzamt anrufen und dringend den Grunderwerbsteuerbescheid beantragen und zahlen" },
  { id: "r77", lvl: 2, text: "VE vergeben  (Fortlaufende 9000er Nummer bei Eigenbestand, 5000er für Kunden die wir vollst. betreuen (immer mit BUHA), für Kapitalanleger ohne BUHA WEG-Objektnr. mit 1 davor, z.B. 1434 bei WEG 434)", verantwortung: "Martin" },
  { id: "r78", lvl: 2, text: "Objektbetreuer zuordnen, aktuell immer Martin", verantwortung: "Martin" },
  { id: "r79", lvl: 2, text: "Objektanlage in Impower, egal ob WEG oder MV (erstellt automatisch sharepoint-Struktur) es soll keine sep Ordnerstruktur (WEG)auf Laufwerk erstellt werden", verantwortung: "Martin" },
  { id: "r80", lvl: 2, text: "WEG: Wirtschaftplan (Hausgeldzahlungen) erstellen, wenn noch keine MEA dann Schlüssel ggf nach Wfl oder Einheiten", verantwortung: "Martin/Julia" },
  { id: "r81", lvl: 2, text: "WEG: MEA`s in impower eintragen", verantwortung: "Martin" },
  { id: "r82", lvl: 2, text: "technische Objektaufnahme mit Verwalter vor Ort (Vordruck: F066)" },
  { id: "r83", lvl: 2, text: "Verwaltervertrag inkl. Festleg.vergütung, Verwaltervollmacht, Bestellungsprotokoll (nur be WEG)", verantwortung: "Martin" },
  { id: "r84", lvl: 2, text: "WEG-Anlage:", verantwortung: "Susanne/ Martin", sub: ["Abrechnungsstandsliste erweitern mit Objekt, Wohnungszähler (Abr. alter EGT oder IVT? Ab wann rechnen wir ab? Abr.-zeitraum? HZK vorhanden?)","gibt es weiter internen Listen zu befüllen? EnBW etc.?"] },
  { id: "r85", lvl: 2, text: "WEG-Bankkonto eröffnet? Verwaltervollmacht und Bestellungsprotokoll notwendig", verantwortung: "Susanne" },
  { id: "r86", lvl: 2, text: "Projektkonto eröffnen, Vorlage XY inkl. Mitteilung Sepa Lastschrift (immer bei allen Konten) -> Obacht bei Mitteilung an Mieter: Geschäftskonto vs. Mietenkonto" },
  { id: "r87", lvl: 2, text: "Impower Mieter mit Name, Kontaktdaten, bankverbindung ggf aus Debitorenliste", verantwortung: "Miranda/Michelle" },
  { id: "r88", lvl: 2, text: "-Brief Anschreiben in ETG erstellen (neue Sendung im MV/WEG? Objekt) und Text aus Vordruck: F047 einsetzen" },
  { id: "r89", lvl: 2, text: "Stammdatenblätter über Paperless einholen und Kontaktdaten in Impower vervollständigen (noch offen im Prozess: Neovaro cc nehmen, dass Sepa direkt in Sharepoint richtig abgelegt wird)" },
  { id: "r90", lvl: 2, text: "WEG: ETG24 Dokumente vervollständigen" },
  { id: "r91", lvl: 2, text: "Aufnahme in Kontenliste - Susanne" },
  { id: "r92", lvl: 2, text: "Ebics (bei jeder neuen Bank) - Susanne beauftragt EBICS (wird benötigt für den Lastschrifteinzug)" },
  { id: "r93", lvl: 2, text: "Datev Integration.- Infos (Mitteilung über neues Objekt mit VE, Adrrese + Eigentümer/Gesellschaft) per Mail an Kathrin" },
  { id: "r94", lvl: 1, text: "Nach Notartermin: Bankthemen" },
  { id: "r95", lvl: 2, text: "Gläubiger ID beantragen und an Bank senden (wird immer benötigt, wenn wir mit Lastschrift einziehen wollen) -> erfolgt durch Susanne", verantwortung: "Susanne" },
  { id: "r96", lvl: 2, text: "Bei Baustelle Verkauf: Erwerber, was ist geplant, welcher Zeitraum und welche Kosten. Vorschlag für umfassenden Versicherungsschutz" },
  { id: "r97", lvl: 2, text: "Grundschuldlöschungsunterlagen" },
  { id: "r98", lvl: 2, text: "Stadt Vorkaufsrecht" },
  { id: "r99", lvl: 2, text: "Fälligkeitsmitteilung liegt vor" },
  { id: "r100", lvl: 2, text: "Datum Kaufpreisfälligkeit" },
  { id: "r101", lvl: 2, text: "Datum Kaufpreiseingang" },
  { id: "r102", lvl: 2, text: "Info Datum Eigentumsübergang an BUHA + Verwaltung" },
  { id: "r103", lvl: 2, text: "Datum des Übergabetermins (Übergabetermin immer Transaktionsleiter + Objektbetreuer)" },
  { id: "r104", lvl: 1, text: "Nach KP-Zahlung: Abschlussarbeiten" },
  { id: "r105", lvl: 2, text: "Versorger anschreiben + SEPA Formular anfordern (alles was nicht in einen Rahmenvertrag kommt mit F065 anschreiben):", sub: ["Müll","alle Wartungsfirmen (bspw. Heizungswartung, Brandschutztüren etc)","Hausmeister/Reinigung","Stadt wg. Niederschlagswasser","Schornsteinfeger","Strom Strom ggf Wasser enbw Portal immo+ Rahmenvertrag: email an XXX, neues Objekt zum Datum","Gas Westbridge Rahmenvertrage: mail an XXX, neues Objekt zum Datum, Anhang Vertrag/lfz Dienstleister und letzte Abr","Wasser","Fernwärme"] },
  { id: "r106", lvl: 2, text: "Versicherung ease Rahmenvertrag: Info an Susanne, neues Objekt zum Datum, Anhang Vertrag/lfz Dienstleister, letzte Prämienrechnung + Versicherungsnachweis -> Meldung an ease durch SB" },
  { id: "r107", lvl: 2, text: "Minol Rahmenvertrag: immer wenn Zentralheizung und Heizkosten abgerechnet werden müssen -> Information direkt an Susanne, dann erfolgt email an Minol durch SB, neues Objekt zum Datum, Info ob Funk, Anhang Vertrag/lfz Dienstleister und letzte Abr \nWEG und MV gleich? Ja" },
  { id: "r108", lvl: 2, text: "Sollstellungen aus Kreditorenliste anlegen in Impower", verantwortung: "Susanne" },
  { id: "r109", lvl: 2, text: "Verkäuferabrechnung inkl. Kautionen einholen" },
  { id: "r110", lvl: 2, text: "Altakten aus Übergabe prüfen, vollständig digitalisieren und alte Dokumente wegwerfen" },
  { id: "r111", lvl: 2, text: "Alle Schlüssel, zuweisen, eindeutig beschriften und Schlüsselbox anlegen" },
  { id: "r112", lvl: 2, text: "Mieterbegrüßungsschreiben erstellen und absenden inkl. Info/ Einladung etg24 - Serienbrief aus ETG durch Nancy" },
  { id: "r113", lvl: 2, text: "Mieterhöhungen (Indexmiete, Staffelmiete, ortsübliche Vergleichsmiete) prüfen und versenden via Paperless" },
  { id: "r114", lvl: 2, text: "Stammdatenblatt von allen" },
  { id: "r115", lvl: 2, text: "Lastschriftmandate mit Paperless und auf Vollständigkeit prüfen" },
  { id: "r117", lvl: 2, text: "Zuständige Person im Objekt festlegen für Zählerstände, ggf Reinigung etc" },
  { id: "r118", lvl: 2, text: "Nachbarschaftsaqkuise: Nachbareigentümer herausfinden und schauen, ob wir weitere Objekte / Einheiten ankaufen können" },
  { id: "r119", lvl: 1, text: "Verkauf anstoßen" },
  { id: "r120", lvl: 2, text: "Kunden und Vertrieb" },
  { id: "r121", lvl: 3, text: "Kundenansprachen wer sind mögliche Kunden aus unserer Kartei? Über welche Vertriebskanäle planen wir zu gehen?" },
  { id: "r122", lvl: 3, text: "Was ist der Case, den wir Verkaufen? Wie ist die Value Proposition? Wieso sollten die Kunden kaufen?" },
  { id: "r123", lvl: 3, text: "Verkaufsliste erstellen und vollständig ausfüllen (bei ETW-Verkauf)" },
  { id: "r124", lvl: 3, text: "Kundenkalkulation erstellen (bei Globalverkauf immer, bei ETW-Verkauf bei Kapitalanlegern). Was ist die Value Proposition? Was sind die Upsights, was die Risiken?" },
  { id: "r125", lvl: 3, text: "Vertriebswege festlegen" },
  { id: "r129", lvl: 2, text: "Projektabwicklung" },
  { id: "r130", lvl: 3, text: "Mietergespräche mit jeder Partei geführt (Vordruck Mietergesprächsliste noch zu erstellen mit touchpoints, Ablauf, todos, Reporting). Mögliche Ziele:", sub: ["freiwillige Mieterhögungen (bspw. Mietentwicklung vorrechnen und Integral von IST zur Sollmiete vorab zahlen; einfach Fragen welche Miete der Mieter sich vorstellen kann; gibt es Themen die den Mieter stören die wir gegen Mieterhöhung beseitigen können?; um Eigenbedarf abzuwenden und Kapitalanleger anzusprechen auch mit Kündigungsverzicht schriftlich)","Kündigungen der Mieter (bspw. konkrete Geldzahlungen anbieten)"] },
  { id: "r131", lvl: 3, text: "Was setzen wir vor dem Verkauf um? Was soll auf Rechnung des Kunden nach Verkauf umgesetzt werden?" },
  { id: "r132", lvl: 3, text: "Welche Budgets sind für das Projekt wofür freigegeben?" },
  { id: "r133", lvl: 2, text: "Verkaufsunterlagen" },
  { id: "r134", lvl: 3, text: "Verkaufsunterlagen vollständig in Propstack auf der richtigen Ebene hochladen (F005)" },
  { id: "r135", lvl: 3, text: "Restnutzungsdauereinschätzung abgelegt" },
  { id: "r136", lvl: 3, text: "Zu allen Kosten: Angebot oder Kostenschätzung / Gutachten und immer Lösung" },
  { id: "r137", lvl: 3, text: "Einwertung Bank (Pascal Götze)" },
  { id: "r138", lvl: 3, text: "Wichtig bei allen Baujahren vor 2005: MFHs: wichtig für die Bankbewertung im Ertragswertverfahren ist die Restnutzungsdauer. Der größte Hebel hier (Vordruck F062):\nPro Punkt: Maßnahme, Zeitpunkt und Gesamtkosten. Maßnahme (x) neu (x) überarbeitet (x) genauere Beschreibung\nSelbst Angabe wie Fassade überarbeitet (gestrichen o.ä.) oder Dach überarbeitet (sauber gemacht) zählt. Hier zählt der technische aber auch der rein optische Zustand.", sub: ["für das Haus:Fassade, Dach, Fenster, Türen, Heizung, Frisch-/Abwasser-/Heizleitungen","ebenso pro Wohnung:"] },
  { id: "r139", lvl: 3, text: "Baubeschreibung in Exposé einfügen (Vordruck F061):", sub: ["Modernisierungsjahre/Instandsetzungsjahre","Geschosse ankreuzen (x) Teilunterkellerung (x) Volunterkellerung (x) Erdgeschoss (x) Obergeschoss(e) (x) nicht ausgebautes Dachgeschoss","Wenn Massivdecken, dann ja, sonst nicht","Fenster Holz / Kunststoff","Verglasung einfach, doppel, dreifach, Isolierglas, Rollläden","Falls separates Gäste-WC, dann angeben"] },
  { id: "r140", lvl: 3, text: "Angebotspreis(e) festlegen (Propstack-Gutachten optional; Individualentscheidung)" },
  { id: "r141", lvl: 3, text: "Professionelle Bilder (Daniel Priess)" },
  { id: "r143", lvl: 3, text: "Grundrisse aufarbeiten (Grundriss.com)" },
  { id: "r144", lvl: 3, text: "Vollständigen Datenraum erstellen (F005)" },
  { id: "r145", lvl: 3, text: "Bei Globalverkauf: klassisches Exposé und Kalkulation mit Case (Value Proposition) (Vorlage erstellen oder Referenzlandingpage festlegen)" },
  { id: "r146", lvl: 3, text: "Bei ETW-Vertrieb: Landingpage / vollständiges Exposé für das Haus mit allen zentralen Unterlagen (Vorlage erstellen oder Referenzlandingpage festlegen) + Onepager pro Einheit mit den spezifischen Unterlagen und dem individuellen Case (Value Proposition) (Vorlage erstellen oder Referenzlandingpage festlegen) + Kalkulation pro Wohnung" },
  { id: "r147", lvl: 1, text: "Falls Projekt nach Verkauf" },
  { id: "r148", lvl: 2, text: "Punkte hier" },
  { id: "bs-final", lvl: 1, text: "vollständig abgearbeitet" },
];
