/** Standard-Checkliste neuer Projekte. Wörtlich aus gg-immohandel src/modules/projektmanagement/pm.ts (PM_TODO_TEMPLATE). */

export interface PmVorlageKategorie { cat: string; items: { text: string; verantw: string }[] }

export const PM_TODO_TEMPLATE: PmVorlageKategorie[] = [
  {cat:'📋 Kaufmännisch / Projekt', items:[
    {text:'Projekt mit allen durchsprechen und Themen zum eruieren sammeln', verantw:''},
    {text:'Projektkosten finalisieren für Kundenangebot.', verantw:''},
    {text:'Restnutzungsdauer kostenlose Einwertung', verantw:''},
    {text:'Kosten für folgende Maßnahmen einholen:\n-\n-', verantw:''},
    {text:'Förderfähigkeit für die Maßnahmen einholen:\n-', verantw:''},
    {text:'Unterlagen für Bankenansprache Kundenseite aufarbeiten', verantw:''},
    {text:'GW Kalkulation für Kunden finalisieren.', verantw:''},
    {text:'Projekt und Verkaufsordner (inkl. Datenraum) anlegen und Unterlagen entsprechend einsortieren', verantw:''},
    {text:'Kundenansprache - wer sind mögliche Kunden aus unserer Kartei? Über welche Vertriebskanäle planen wir zu gehen?', verantw:''},
  ]},
  {cat:'📊 Steuerliche Due Diligence', items:[
    {text:'Kaufpreisanteil Grund und Boden\n-im Ankauf keine Aufteilung', verantw:''},
  ]},
  {cat:'⚖️ Rechtliche Due Diligence', items:[
    {text:'Mietverträge und Nachträge prüfen', verantw:''},
    {text:'Auflistung aller weiterer Dokumente aus Datenraum / Datenpaket, die geprüft werden müssen:', verantw:''},
    {text:'Grundbuchauszug prüfen', verantw:''},
    {text:'Teilungserklärung und Teilungspläne prüfen', verantw:''},
    {text:'Bewilligungsurkunden für alle Grunddienstbarkeiten anfordern & prüfen', verantw:''},
    {text:'Kaufvertragsentwurf vorhanden?', verantw:''},
    {text:'Kaufvertragsentwurf intern prüfen\n-langes Zahlungsziel mind. 3 Monate\n-Vollmacht gegenüber Baurechtsamt auf eigene Kosten und Risiko Bauanträge zu stellen?', verantw:''},
    {text:'Kaufvertrag final freigegeben', verantw:''},
    {text:'Datenraum vollständig plausibilisieren und hier zu klärende Fragen notieren', verantw:''},
    {text:'Verwaltervertrag abschließen', verantw:''},
    {text:'Projektkonto eröffnet? - muss spätestens nach Notartermin eröffnet werden\n_9000er macht Alisa\n_5000er macht Susanne', verantw:''},
    {text:'Notartermin Datum:', verantw:''},
    {text:'Track Record Tabelle aktualisiert', verantw:''},
  ]},
  {cat:'🔧 Technische Due Diligence', items:[
    {text:'Wird eine technische DD benötigt?', verantw:''},
    {text:'Ist der letzte genehmigte Stand mit der aktuellen Nutzung übereinstimmend?', verantw:''},
    {text:'Sind alle Baugenehmigungen mit Stempel vorhanden?', verantw:''},
    {text:'Sind alle Grundrisse mit Stempel vorhanden?', verantw:''},
    {text:'Gibt es eine gestempelte Flächenberechnung eines Architekten?', verantw:''},
    {text:'Flächen plausibilisieren mit eigenem Aufmaß der Grundrisse und/oder Referenzmaßen vor Ort', verantw:''},
    {text:'Baulasten prüfen', verantw:''},
    {text:'Negativzeugnis Denkmalschutz', verantw:''},
    {text:'Altlasten prüfen', verantw:''},
    {text:'Gebäudeversicherungsnachweis', verantw:''},
    {text:'Energieausweis vorhanden?', verantw:''},
  ]},
  {cat:'🏦 Finanzierung und KP-Zahlung', items:[
    {text:'Liquiditätsplanung und Projektkosten festlegen', verantw:''},
    {text:'Welche Kosten sind für das Projekt budgetiert und freigegeben', verantw:''},
    {text:'EK-Anteil an Bank kommuniziert:\nEK-Anteil zusätzlich eingeplant:', verantw:''},
    {text:'FK Anteil:', verantw:''},
    {text:'Finanzierungspräsentation erstellen', verantw:''},
    {text:'Inhalte Finanzierungspräsentation füllen', verantw:''},
    {text:'Kalkulation für Bank', verantw:''},
    {text:'Energieausweis', verantw:''},
    {text:'Baugenehmigung als 1 PDF', verantw:''},
    {text:'Flächenberechnung als 1 PDF', verantw:''},
    {text:'Gestempelte Grundrisse als 1 PDF', verantw:''},
    {text:'Gebäudeversicherungsnachweis', verantw:''},
    {text:'Welche Gesellschaft kauft?', verantw:''},
    {text:'Kreditanfrage stellen', verantw:''},
    {text:'Grundschuld enge Zweckerklärung', verantw:''},
    {text:'Grundschuld Anteil vollstreckbar und nicht vollstreckbar', verantw:''},
    {text:'Quotale Rückführung vereinbaren', verantw:''},
    {text:'Bank mitteilen, dass in der Zukunft saniert wird für Aufbau/Sanierungsfinanzierung', verantw:''},
    {text:'Kreditvertrag abgeschlossen', verantw:''},
    {text:'Grundschuldbestellungsunterlagen vor dem Notartermin erhalten', verantw:''},
    {text:'Bank informieren über welches Konto Darlehensrate eingezogen wird', verantw:''},
  ]},
  {cat:'💻 Nach Notartermin: Systemintegration', items:[
    {text:'Notartermin Nachbesprechen', verantw:''},
    {text:'Info mit Ankündigung + wichtigen Infos an Team (Buha Susanne + Verwaltung Miranda/Benjamin + Transaktion Martin/Benjamin, Mietmanagement Michelle)', verantw:''},
    {text:'KV-Abschrift in DATEV (Alisa)', verantw:''},
    {text:'Finanzamt anrufen und dringend den Grunderwerbsteuerbescheid beantragen und zahlen', verantw:''},
    {text:'VE vergeben (Fortlaufende 9000er Nummer bei Eigenbestand, 5000er für Kunden die wir vollst. betreuen, für Kapitalanleger ohne BUHA WEG-Objektnr. mit 1 davor)', verantw:'Martin'},
    {text:'Debitorenlisten vollständig bei Verkäufer anfordern oder erstellen', verantw:''},
    {text:'Kreditorenlisten vollständig bei Verkäufer anfordern oder erstellen', verantw:''},
    {text:'Objektbetreuer zuordnen, aktuell immer Martin', verantw:'Martin'},
    {text:'WEG / MV Struktur anlegen', verantw:''},
    {text:'Objektanlage in Impower (erstellt automatisch Sharepoint-Struktur)', verantw:'Martin'},
    {text:'WEG: Wirtschaftplan erstellen, wenn noch keine MEA dann Schlüssel ggf nach Wfl oder Einheiten', verantw:'Martin/Julia'},
    {text:'WEG: MEAs in Impower eintragen', verantw:'Martin'},
    {text:'Technische Objektaufnahme mit Verwalter vor Ort, Vordruck Übernahmecheckliste verwenden', verantw:'Martin'},
    {text:'Verwaltervertrag inkl. Vergütung, Verwaltervollmacht, Bestellungsprotokoll (nur bei WEG)', verantw:'Martin'},
    {text:'WEG-Anlage:\n-Abrechnungsstandsliste erweitern mit Objekt, Wohnungszähler\n-gibt es weitere interne Listen zu befüllen? EnBW etc.?', verantw:'Susanne/Martin'},
    {text:'WEG-Bankkonto eröffnet? Verwaltervollmacht und Bestellungsprotokoll notwendig', verantw:'Susanne'},
    {text:'Projektkonto eröffnen, Vorlage XY inkl. Mitteilung Sepa Lastschrift', verantw:''},
    {text:'Impower Mieter mit Name, Kontaktdaten, Bankverbindung ggf aus Debitorenliste', verantw:'Miranda/Michelle'},
    {text:'E-Mail-Adressen aller Mieter einsammeln:\n-Brief Anschreiben in ETG erstellen\n-beim Verkäufer nachfragen\n-Mietverträge auf Email prüfen', verantw:'Miranda/Michelle'},
    {text:'Impower Debitoren Sollstellungen anlegen', verantw:'Miranda/Michelle'},
    {text:'SEPA-Mandate über Paperless einholen', verantw:''},
    {text:'Stammdatenblätter über Paperless einholen und Kontaktdaten in Impower vervollständigen', verantw:''},
    {text:'ETG24 Dokumente vervollständigen', verantw:''},
    {text:'Windows Integration: alle Unterlagen OCR konvertieren + Projektordnerstruktur anlegen (NACH OCR!)', verantw:''},
    {text:'Aufnahme in Kontenliste - Alisa', verantw:''},
    {text:'Ebics (bei jeder neuen Bank) - Alisa', verantw:''},
    {text:'Datev Integration - Alisa', verantw:''},
  ]},
  {cat:'🏦 Nach Notartermin: Bankthemen', items:[
    {text:'Gläubiger ID beantragen und an Bank senden', verantw:''},
    {text:'Bei Baustelle Verkauf: Erwerber, was ist geplant, welcher Zeitraum und welche Kosten. Vorschlag für umfassenden Versicherungsschutz', verantw:''},
    {text:'Grundschuldlöschungsunterlagen', verantw:''},
    {text:'Stadt Vorkaufsrecht', verantw:''},
    {text:'Fälligkeitsmitteilung liegt vor', verantw:''},
    {text:'Ankauf mit erweitertem Team abstimmen. Was haben wir vor, wie soll kommuniziert werden, was sind die Ziele?', verantw:''},
    {text:'Datum Kaufpreisfälligkeit', verantw:''},
    {text:'Datum Kaufpreiseingang', verantw:''},
    {text:'Info Datum Eigentumsübergang an BUHA + Verwaltung', verantw:''},
    {text:'Datum des Übergabetermins (immer Transaktionsleiter + Objektbetreuer)', verantw:''},
  ]},
  {cat:'🔑 Nach KP-Zahlung: Abschlussarbeiten', items:[
    {text:'Versorger anschreiben + SEPA Formular anfordern; Müll, alle Wartungsfirmen, Hausmeister/Reinigung, Stadt wg. Niederschlagswasser', verantw:''},
    {text:'Strom ggf Wasser EnBW Portal immo+ Rahmenvertrag: email an XXX, neues Objekt zum Datum', verantw:''},
    {text:'Versicherung EAS Rahmenvertrag: email an XXX, neues Objekt zum Datum', verantw:''},
    {text:'Gas Westbridge Rahmenvertrag: mail an XXX, neues Objekt zum Datum', verantw:''},
    {text:'Minol Rahmenvertrag: email an Kim-Luca.Quattrone@minol.com, neues Objekt zum Datum', verantw:''},
    {text:'Sollstellungen aus Kreditorenliste anlegen in Impower', verantw:'Susanne'},
    {text:'Mieteinheiten: technische Objektaufnahme mit Verwalter vor Ort, Vordruck Übernahmecheckliste', verantw:'Martin'},
    {text:'Termin in 4-6 Wochen für Review Eigentumswechsel (ist alles umgemeldet, funktionieren alle Konten, zahlen alle Mieter?)', verantw:''},
    {text:'Verkäuferabrechnung inkl. Kautionen einholen', verantw:''},
    {text:'Altakten aus Übergabe prüfen, vollständig digitalisieren und alte Dokumente wegwerfen', verantw:''},
    {text:'Vollständige Bestandsaufnahme & Bilder von jeder Wohnung', verantw:''},
    {text:'Alle Schlüssel zuweisen, eindeutig beschriften und Schlüsselbox anlegen', verantw:''},
    {text:'Mieterbegrüßungsschreiben erstellen und absenden inkl. Info/Einladung ETG24', verantw:''},
    {text:'Stammdatenblatt von allen', verantw:''},
    {text:'Lastschriftmandate mit Paperless und auf Vollständigkeit prüfen', verantw:''},
    {text:'Zählerstände Strom/Gas ablesen und an Anbieter weiterleiten', verantw:''},
    {text:'Gebäudeversicherung kündigen und auf SV-Rahmenvertrag umstellen', verantw:''},
    {text:'Schornsteinfeger informieren', verantw:''},
    {text:'Zuständige Person im Objekt festlegen für Zählerstände, ggf Reinigung etc', verantw:''},
    {text:'Nachbarschaftsakquise: Nachbareigentümer herausfinden und schauen, ob wir weitere Objekte ankaufen können', verantw:''},
  ]},
  {cat:'📣 Verkauf anstoßen', items:[
    {text:'Kundenansprachen: wer sind mögliche Kunden? Über welche Vertriebskanäle planen wir zu gehen?', verantw:''},
    {text:'Was ist der Case, den wir verkaufen? Wie ist die Value Proposition?', verantw:''},
    {text:'Verkaufsliste erstellen und vollständig ausfüllen (bei ETW-Verkauf)', verantw:''},
    {text:'Kundenkalkulation erstellen (bei Globalverkauf immer, bei ETW-Verkauf bei Kapitalanlegern)', verantw:''},
    {text:'Vertriebswege festlegen', verantw:''},
    {text:'Makler Vertrag unterschrieben', verantw:''},
    {text:'Datenraum an Makler', verantw:''},
    {text:'Zahlungsziel Verkäuferprovision mit Kaufpreiseingang mit Makler abstimmen', verantw:''},
    {text:'Mietergespräche mit jeder Partei geführt\n-freiwillige Mieterhöhungen (Mietentwicklung vorrechnen, Integralzahlung, Themen beseitigen, Kündigungsverzicht)\n-Kündigungen der Mieter (konkrete Geldzahlungen anbieten)', verantw:''},
    {text:'Was setzen wir vor dem Verkauf um? Was soll auf Rechnung des Kunden nach Verkauf umgesetzt werden?', verantw:''},
    {text:'Welche Budgets sind für das Projekt wofür freigegeben?', verantw:''},
    {text:'Verkaufsunterlagen vollständig in Propstack hochladen (F005 / F006)', verantw:''},
    {text:'Restnutzungsdauereinschätzung abgelegt', verantw:''},
    {text:'Zu allen Kosten: Angebot oder Kostenschätzung / Gutachten und immer Lösung', verantw:''},
    {text:'Einwertung Bank (Pascal Götze)', verantw:''},
    {text:'Restnutzungsdauer für Bankbewertung dokumentieren (Baujahr vor 2005):\n-Fassade, Dach, Fenster, Türen, Heizung, Leitungen\n-pro Wohnung: Maßnahme, Zeitpunkt, Kosten', verantw:''},
    {text:'Baubeschreibung in Exposé einfügen:\n-Modernisierungsjahre\n-Geschosse, Keller, Fenster, Verglasung, Rollläden', verantw:''},
    {text:'Angebotspreis(e) festlegen', verantw:''},
    {text:'Professionelle Bilder (Backbone)', verantw:''},
    {text:'Visualisierungen (Giulia Ganzaroli)', verantw:''},
    {text:'Grundrisse aufarbeiten (Grundriss.com)', verantw:''},
    {text:'Vollständigen Datenraum erstellen (F005)', verantw:''},
    {text:'Bei Globalverkauf: klassisches Exposé und Kalkulation mit Case (Value Proposition)', verantw:''},
    {text:'Bei ETW-Vertrieb: Landingpage + Onepager pro Einheit mit individuellem Case + Kalkulation pro Wohnung', verantw:''},
  ]},
]
